/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class App {
    public static void main(String[] args) {
        List<Integer> nums1 = List.of(1, 3, 5, 7);
        List<Integer> nums2 = List.of(2, 4, 6, 8);
        List<Integer> mergedNumbers = ListUtils.zip(nums1, nums2);
        System.out.println("Merged integers: " + mergedNumbers);
        
        List<String> colors1 = List.of("Red", "Green", "Blue");
        List<String> colors2 = List.of("White", "Black", "Orange", "Pink", "Fuschia");
        List<String> mergedColors = ListUtils.zip(colors1, colors2);
        System.out.println("Merged colors: " + mergedColors);
        
        List<Double> emptyList = List.of();
        List<Double> doubles = List.of(1.1, 2.2, 3.3);
        List<Double> mergedDoubles = ListUtils.zip(emptyList, doubles);
        System.out.println("Merged with empty list: " + mergedDoubles);
    }
}